pipeline{
    agent any

    stages{
        stage("clean up"){
            steps{
                deleteDir()
            }
        }
        stage("Build"){
            steps{
                dir("serenity-junit-tutorial"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("serenity-junit-tutorial"){
                    sh "mvn test"
                }
            }
        }
    }
}
